development:
  adapter: mysql2
  encoding: utf8
  database: Development
  username: root
  password: lorde1234
  host: 127.0.0.1
  port: 3306

Production:
  adapter: mysql2
  encoding: utf8
  database: Production
  username: root
  password: lorde1234
  host: 127.0.0.1
  port: 3306

Test:
  adapter: mysql2
  encoding: utf8
  database: Test
  username: root
  password: lorde1234
  host: 127.0.0.1
  port: 3306
